backend:
  name: git-gateway
  branch: main
media_folder: "public/images"
public_folder: "/images"
collections:
  name: "blog"
  label: "Blog"
  folder: "src/blog"
  create: true
  slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
  fields:
    - { label: "Title", name: "title", widjet: "string" }
    - { label: "Description", name: "description", widjet: "string" }
    - { label: "Author", name: "author", widjet: "string" }
    - { label: "Date", name: "date", widjet: "datetime" }
    - { label: "Tags", name: "tags", widjet: "list", default: ["post"] }
    - { label: "Featured Image", name: "image", widjet: "image" }
    - { label: "Image caption", name: "imageAlt", widjet: "string" }
    - { label: "Body", name: "body", widjet: "markdown" }